// Component manifest for initialization
export const manifest = {
  // Indicators
  circular_gauge: true,
  cond_SCRAM: true,
  cond_POWER: true,
  cond_FAULT: true,
  cond_TEST: true,
  cond_STANDBY: true,
  cond_RUN: true,
  cond_WARN: true,
  cond_LOCKED: true,
  cond_AUX: true,
  cond_COOL: true,

  // Digital displays
  digi_0: true,
  digi_1: true,
  digi_2: true,
  digi_3: true,
  digi_4: true,
  digi_5: true,
  digi_6: true,
  digi_7: true,
  digi_8: true,
  digi_9: true,
  digi_10: true,
  digi_11: true,
  digi_12: true,
  digi_13: true,
  digi_14: true,

  // Blink indicators
  blink_opr_left: true,
  blink_opr_right: true,
  blink_grid_0: true,
  blink_grid_1: true,
  blink_grid_2: true,
  blink_grid_3: true,
  blink_grid_4: true,
  blink_grid_5: true,
  blink_grid_6: true,
  blink_grid_7: true,
  blink_grid_8: true,
  blink_grid_9: true,
  blink_grid_10: true,
  blink_grid_11: true,
  blink_grid_12: true,
  blink_grid_13: true,
  blink_grid_14: true,
  blink_grid_15: true,
  blink_grid_16: true,
  blink_grid_17: true,

  // Sliders
  slider_0: true,
  slider_1: true,
  slider_2: true,
  slider_3: true,
  slider_4: true,
  slider_5: true,
  slider_6: true,
  slider_7: true,

  // Knobs
  knob_grid_0: true,
  knob_grid_1: true,
  knob_grid_2: true,
  knob_grid_3: true,
  knob_grid_4: true,
  knob_grid_5: true,
  knob_grid_6: true,
  knob_grid_7: true,
  knob_grid_8: true,
  knob_grid_9: true,
  knob_grid_10: true,
  knob_grid_11: true,
  knob_grid_12: true,
  knob_grid_13: true,
  knob_grid_14: true,
  knob_ind_0: true,
  knob_ind_1: true,

  // Master control
  master: true,

  // Fuel rod buttons
  fuel_rod_button_0_0: true,
  fuel_rod_button_1_0: true,
  fuel_rod_button_2_0: true,
  fuel_rod_button_3_0: true,
  fuel_rod_button_4_0: true,
  fuel_rod_button_5_0: true,
  fuel_rod_button_0_1: true,
  fuel_rod_button_1_1: true,
  fuel_rod_button_2_1: true,
  fuel_rod_button_3_1: true,
  fuel_rod_button_4_1: true,
  fuel_rod_button_5_1: true,
  fuel_rod_button_0_2: true,
  fuel_rod_button_1_2: true,
  fuel_rod_button_2_2: true,
  fuel_rod_button_3_2: true,
  fuel_rod_button_4_2: true,
  fuel_rod_button_5_2: true,
  fuel_rod_button_0_3: true,
  fuel_rod_button_1_3: true,
  fuel_rod_button_2_3: true,
  fuel_rod_button_3_3: true,
  fuel_rod_button_4_3: true,
  fuel_rod_button_5_3: true,
  fuel_rod_button_0_4: true,
  fuel_rod_button_1_4: true,
  fuel_rod_button_2_4: true,
  fuel_rod_button_3_4: true,
  fuel_rod_button_4_4: true,
  fuel_rod_button_5_4: true,
  fuel_rod_button_0_5: true,
  fuel_rod_button_1_5: true,
  fuel_rod_button_2_5: true,
  fuel_rod_button_3_5: true,
  fuel_rod_button_4_5: true,
  fuel_rod_button_5_5: true,

  // Auxiliary buttons
  aux_button_0: true,
  aux_button_1: true,
  aux_button_2: true,
  aux_button_3: true,
  aux_button_4: true,
  aux_button_5: true
} as const;

export type ComponentId = keyof typeof manifest;
