const initComponentIds = [
  'circular_gauge',

  'cond_SCRAM',
  'cond_POWER',
  'cond_FAULT',
  'cond_TEST',
  'cond_STANDBY',
  'cond_RUN',
  'cond_WARN',
  'cond_LOCKED',
  'cond_AUX',
  'cond_COOL',

  'digi_0', 'digi_1', 'digi_2', 'digi_3', 'digi_4', 'digi_5',
  'digi_6', 'digi_7', 'digi_8', 'digi_9', 'digi_10', 'digi_11',
  'digi_12', 'digi_13', 'digi_14',

  'blink_opr_left',
  'blink_opr_right',
  'blink_grid_0',
  'blink_grid_1',
  'blink_grid_2',
  'blink_grid_3',
  'blink_grid_4',
  'blink_grid_5',
  'blink_grid_6',
  'blink_grid_7',
  'blink_grid_8',
  'blink_grid_9',
  'blink_grid_10',
  'blink_grid_11',
  'blink_grid_12',
  'blink_grid_13',
  'blink_grid_14',
  'blink_grid_15',
  'blink_grid_16',
  'blink_grid_17',

  'slider_0',
  'slider_1',
  'slider_2',
  'slider_3',
  'slider_4',
  'slider_5',
  'slider_6',
  'slider_7',

  'knob_grid_0', 'knob_grid_1', 'knob_grid_2', 'knob_grid_3',
  'knob_grid_4', 'knob_grid_5', 'knob_grid_6', 'knob_grid_7',
  'knob_grid_8', 'knob_grid_9', 'knob_grid_10', 'knob_grid_11',
  'knob_grid_12', 'knob_grid_13', 'knob_grid_14',
  'knob_ind_0', 'knob_ind_1',

  'master',

  'panel_btn_grid_0', 'panel_btn_grid_1', 'panel_btn_grid_2', 'panel_btn_grid_3',
  'panel_btn_grid_4', 'panel_btn_grid_5', 'panel_btn_grid_6', 'panel_btn_grid_7',
  'panel_btn_grid_8', 'panel_btn_grid_9', 'panel_btn_grid_10', 'panel_btn_grid_11',
  'panel_btn_grid_12', 'panel_btn_grid_13', 'panel_btn_grid_14', 'panel_btn_grid_15',
  'panel_btn_grid_16', 'panel_btn_grid_17', 'panel_btn_grid_18', 'panel_btn_grid_19',
  'panel_btn_grid_20', 'panel_btn_grid_21', 'panel_btn_grid_22', 'panel_btn_grid_23',
  'panel_btn_grid_24', 'panel_btn_grid_25', 'panel_btn_grid_26', 'panel_btn_grid_27',
  'panel_btn_grid_28', 'panel_btn_grid_29', 'panel_btn_grid_30', 'panel_btn_grid_31',
  'panel_btn_grid_32', 'panel_btn_grid_33', 'panel_btn_grid_34', 'panel_btn_grid_35',

  'panel_btn_strip_0', 'panel_btn_strip_1', 'panel_btn_strip_2',
  'panel_btn_strip_3', 'panel_btn_strip_4', 'panel_btn_strip_5',

  'scram',

  'meter_0', 'meter_1', 'meter_2', 'meter_3', 'meter_4',
];

export default initComponentIds;
